name: Node.js Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Create Tag
        id: create_tag
        uses: jaywcjlove/create-tag-action@v1.3.6
        with:
          package-path: ./package.json

      - name: Create Release
        uses: ncipollo/release-action@v1
        if: steps.create_tag.outputs.successful
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ steps.create_tag.outputs.version }}
          tag: ${{ steps.create_tag.outputs.version }}

      # - run: npm ci
      # - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com
          scope: '@jaywcjlove'
      # - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Modify package name
        shell: bash
        run: |
          node -e 'var pkg = require("./package.json"); pkg.name="@jaywcjlove/hello-world-npm-app"; require("fs").writeFileSync("./package.json", JSON.stringify(pkg, null, 2))'

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Modify package name
        shell: bash
        run: |
          node -e 'var pkg = require("./package.json"); pkg.name="@jaywcjlove/hello-world-npm-test"; require("fs").writeFileSync("./package.json", JSON.stringify(pkg, null, 2))'

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}