name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      # - run: npm ci
      # - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com
          scope: '@jaywcjlove'
      # - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Modify package name
        shell: bash
        run: |
          node -e 'var pkg = require("./package.json"); pkg.name="@jaywcjlove/hello-world-npm-app"; require("fs").writeFileSync("./package.json", JSON.stringify(pkg, null, 2))'

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Modify package name
        shell: bash
        run: |
          node -e 'var pkg = require("./package.json"); pkg.name="@jaywcjlove/hello-world-npm-test"; require("fs").writeFileSync("./package.json", JSON.stringify(pkg, null, 2))'

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}